/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nihil.RockPaperScissors;

/**
 *
 * @author LATITUDE 5410
 */
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;

public class UsermanualsPln extends javax.swing.JFrame {

    /**
     * Creates new form UsermanualsPln
     */
    public UsermanualsPln() {
        this.setUndecorated(true);
        this.setResizable(false);
        this.setTitle("USERMANUALS");
        initComponents();
        refactor();
        editingLabelIcons();
    }

    private void refactor(){
        gamemanualsLbl.setEnabled(false);
        gamemanualsLbl.setEditable(false);
        gamemanualsLbl.setBorder(null);
       // gamemanualsLbl.setBackground(Color.red);
        
        shortcutPnl.setEnabled(false);
        shortcutPnl.setEditable(false);
        shortcutPnl.setBorder(null);
        
        gameInfoLbl.setEnabled(false);
        gameInfoLbl.setEditable(false);
        gameInfoLbl.setBorder(null);
    }
    
    private void editingLabelIcons() {
        try {
            JLabel[] pictureLbl = new JLabel[]{rockImg, paperImg, scissorsImg};
            String[] iconURLs = new String[]{"C:\\Users\\LATITUDE 5410\\netBeans\\netBeans-Programs\\ROCK_PAPER_SCISSORS\\src\\main\\java\\Images\\rockImg.png",
                                             "C:\\Users\\LATITUDE 5410\\netBeans\\netBeans-Programs\\ROCK_PAPER_SCISSORS\\src\\main\\java\\Images\\paperImg.png",
                                             "C:\\Users\\LATITUDE 5410\\netBeans\\netBeans-Programs\\ROCK_PAPER_SCISSORS\\src\\main\\java\\Images\\scissorImg.png"};
            for (int run = 0; run < pictureLbl.length; run++) {
                BufferedImage imgPlay = ImageIO.read(new File(iconURLs[run]));
                Image sizedImgPlay = imgPlay.getScaledInstance(pictureLbl[run].getWidth() - 0, pictureLbl[run].getHeight() - 0, Image.SCALE_SMOOTH);
                ImageIcon iconPlay = new ImageIcon(sizedImgPlay);
                pictureLbl[run].setIcon(iconPlay);
            }
        } catch (Exception error) {
            System.out.println(error.getMessage());
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameInfoLbl = new javax.swing.JTextArea();
        paperImg = new javax.swing.JLabel();
        scissorsImg = new javax.swing.JLabel();
        rockImg = new javax.swing.JLabel();
        headerLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        shortcutPnl = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        gamemanualsLbl = new javax.swing.JTextArea();
        exitControl = new javax.swing.JLabel();
        rockLbl = new javax.swing.JLabel();
        paperLbl = new javax.swing.JLabel();
        scissorsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new java.awt.Color(255, 255, 255));

        gameInfoLbl.setBackground(new java.awt.Color(41, 41, 41));
        gameInfoLbl.setColumns(20);
        gameInfoLbl.setForeground(new java.awt.Color(0, 0, 0));
        gameInfoLbl.setRows(5);
        gameInfoLbl.setText("\nGENRES : HAND GAME\n-----------------------------\nPLAYERS : 1-M\n-----------------------------\nSETUP TIME : NONE\n-----------------------------\nPLAYING TIME : SECONDS\n------------------------------\nCHANCE : NONE TO SOME\n------------------------------");
        gameInfoLbl.setAutoscrolls(false);
        gameInfoLbl.setBorder(null);
        gameInfoLbl.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(gameInfoLbl);

        paperImg.setBackground(new java.awt.Color(51, 51, 51));

        scissorsImg.setBackground(new java.awt.Color(51, 51, 51));

        rockImg.setBackground(new java.awt.Color(51, 51, 51));

        headerLbl.setFont(new java.awt.Font("Showcard Gothic", 0, 20)); // NOI18N
        headerLbl.setForeground(new java.awt.Color(0, 0, 0));
        headerLbl.setText("USER MANUAL");

        shortcutPnl.setBackground(new java.awt.Color(41, 41, 41));
        shortcutPnl.setColumns(20);
        shortcutPnl.setForeground(new java.awt.Color(0, 0, 0));
        shortcutPnl.setRows(5);
        shortcutPnl.setText("SHORTCUT MANUAL\n-------------------------\nR -> Throws ROCK\nS -> Throws SCISSORS\nP -> Throws PAPER");
        shortcutPnl.setBorder(null);
        shortcutPnl.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(shortcutPnl);

        gamemanualsLbl.setBackground(new java.awt.Color(41, 41, 41));
        gamemanualsLbl.setColumns(20);
        gamemanualsLbl.setForeground(new java.awt.Color(0, 0, 0));
        gamemanualsLbl.setRows(5);
        gamemanualsLbl.setText("INSTRUCTIONS\n------------------\n------------------\nROCK : A closed fist\nPAPER : A flat hand\nSCISSORS : A fist with the index finger and middle finger exteded.\n\n-------------------------------------------------------------------------\nPOSSIBLE OUTCOMES\n------------------------\n------------------------\nDRAW - WIN - LOSE\n\n------------------------------------------------------------------------\nPLAY\n-----------------------\n-----------------------\nROCK -> BEAT -> SCISSORS      : (Rock breaks or crushes scissors)\nPAPER -> BEAT -> ROCK            :  (Paper covers rock)\nSCISSORS -> BEAT -> PAPER     : (Scissors cut paper)");
        gamemanualsLbl.setBorder(null);
        gamemanualsLbl.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        gamemanualsLbl.setEnabled(false);
        jScrollPane1.setViewportView(gamemanualsLbl);

        exitControl.setBackground(new java.awt.Color(41, 41, 41));
        exitControl.setFont(new java.awt.Font("Showcard Gothic", 0, 26)); // NOI18N
        exitControl.setForeground(new java.awt.Color(204, 204, 204));
        exitControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitControl.setText("X");
        exitControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitControlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitControlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitControlMouseExited(evt);
            }
        });

        rockLbl.setForeground(new java.awt.Color(0, 0, 0));
        rockLbl.setText("ROCK SIGN");

        paperLbl.setForeground(new java.awt.Color(0, 0, 0));
        paperLbl.setText("PAPER SIGN");

        scissorsLbl.setForeground(new java.awt.Color(0, 0, 0));
        scissorsLbl.setText("SCISSORS SIGN");

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scissorsImg, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paperImg, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rockImg, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(paperLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                        .addComponent(rockLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(scissorsLbl))
                                .addGap(197, 197, 197)))))
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitControl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(headerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(contentPaneLayout.createSequentialGroup()
                                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rockImg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rockLbl))
                                        .addGap(22, 22, 22)
                                        .addComponent(paperImg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(paperLbl))
                                .addGap(20, 20, 20)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scissorsImg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scissorsLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(exitControl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitControlMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitControlMouseClicked

    private void exitControlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitControlMouseEntered
        exitControl.setForeground(Color.RED);
        exitControl.setFont(new Font("Showcard Gothic", Font.PLAIN | Font.BOLD, 28));
    }//GEN-LAST:event_exitControlMouseEntered

    private void exitControlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitControlMouseExited
        exitControl.setForeground(new Color(204,204,204));
        exitControl.setFont(new Font("Showcard Gothic", Font.PLAIN, 22));
    }//GEN-LAST:event_exitControlMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel exitControl;
    private javax.swing.JTextArea gameInfoLbl;
    private javax.swing.JTextArea gamemanualsLbl;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel paperImg;
    private javax.swing.JLabel paperLbl;
    private javax.swing.JLabel rockImg;
    private javax.swing.JLabel rockLbl;
    private javax.swing.JLabel scissorsImg;
    private javax.swing.JLabel scissorsLbl;
    private javax.swing.JTextArea shortcutPnl;
    // End of variables declaration//GEN-END:variables
}
